import { Cormorant } from "next/font/google";
import "./globals.css";
import Navbar from "@/Shared/Navbar";

const cormorant = Cormorant({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cormorant.className} antialiased relative`}>
        <div className="absolute top-0 left-0 right-0 z-10">
          <Navbar />
        </div>
        <div className="">{children}</div>
      </body>
    </html>
  );
}
